### ISSUE TITLE
Lock on package SB-DI violated 

### ISSUE THREAD

**Issue by djireland** [Shinmera/dissect#20]
Loading Dissect on SBCL 2.4.3 using:

`(QL:QUICKLOAD :DISSECT)`

Results in: 

caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Lock on package SB-DI violated when interning DEBUG-VAR-INFO while in package
;     DISSECT.
;   See also:
;     The SBCL Manual, Node "Package Locks"
;   
;     (in form starting at line: 38, column: 0, position: 1539)
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1001FE4653}>.

**Comment by Shinmera** [comment]
Please read existing issues first before reporting.

#19 #18
