### ISSUE TITLE
dissect doesn't load on sbcl

### ISSUE THREAD

**Issue by ormf** [Shinmera/dissect#6]
`(ql:quickload "dissect")
To load "dissect":
  Load 1 ASDF system:
    dissect
; Loading "dissect"
; 
; caught ERROR:
;   READ error during COMPILE-FILE:
;   
;     Symbol "DEBUG-SOURCE-FORM" not found in the SB-DI package.
;   
;       Line: 18, Column: 43, File-Position: 562
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file <home>/quicklisp/dists/quicklisp/software/dissect-20180131-git/backend/sbcl.lisp" {1003BA0C93}>
; 
; compilation unit aborted
;   caught 2 fatal ERROR conditions
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1003BBB1F3}>.
CL-USER> 

`

**Comment by Shinmera** [comment]
This was fixed in 85f9d485cca892dec12f365505251ac0d1c2c26b
